"""Sprint 23 — Exam style profile seeds (estimated official-exam characteristics).

NO copyrighted question text. Statistical / stylistic targets only.
"""

from __future__ import annotations

from typing import Any


def _avoid_common() -> list[str]:
    return [
        "simple textbook wording",
        "childish examples",
        "obvious wrong options",
        "copy existing exam questions",
        "refer to missing paragraph/table",
        "ChatGPT-style filler phrases",
    ]


def build_exam_style_seed() -> list[dict[str, Any]]:
    """Return list of exam_style_profiles (+ optional stats)."""
    return [
        {
            "exam_code": "kpss",
            "name": "KPSS",
            "question_format": "mixed",
            "paragraph_words_min": 80,
            "paragraph_words_max": 220,
            "stem_words_min": 18,
            "stem_words_max": 90,
            "option_words_min": 3,
            "option_words_max": 28,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "analyze",
            "language_level": "formal_tr_public",
            "reading_time_sec_avg": 75,
            "difficulty_band_default": "high",
            "distractor_types": [
                "meaning_shift",
                "half_correct",
                "scope_shift",
                "terminology_confusion",
                "opposite_logic",
            ],
            "style_rules": {
                "tone": "ÖSYM resmi kamu sınavı",
                "prefer_inference": True,
                "self_contained_stem": True,
                "paragraph_first_when_reading": True,
                "option_similarity": "medium_high",
                "option_style": "parallel_length",
                "wording_style": "formal_osym_public",
                "abstraction_level": "moderate_high",
                "inference_ratio": 0.58,
                "elimination_ratio": 0.42,
                "bloom_distribution": {
                    "analyze": 0.45,
                    "apply": 0.25,
                    "understand": 0.2,
                    "evaluate": 0.1,
                },
                "reasoning_distribution": {
                    "inference": 0.4,
                    "comparison": 0.15,
                    "elimination": 0.3,
                    "main_idea": 0.15,
                },
                "skill_distribution": {
                    "vocabulary": 0.08,
                    "sentence_meaning": 0.08,
                    "main_idea": 0.1,
                    "supporting_idea": 0.1,
                    "paragraph_completion": 0.1,
                    "sentence_ordering": 0.08,
                    "coherence": 0.08,
                    "grammar": 0.1,
                    "spelling": 0.08,
                    "punctuation": 0.08,
                    "logic": 0.06,
                    "mixed_reasoning": 0.06,
                },
                "difficulty_distribution": {"easy": 0.15, "medium": 0.45, "hard": 0.4},
                "stem_type_distribution": {
                    "inference": 0.25,
                    "main_idea": 0.15,
                    "paragraph_completion": 0.12,
                    "sentence_ordering": 0.1,
                    "grammar": 0.12,
                    "vocabulary": 0.1,
                    "comparison": 0.08,
                    "logic": 0.08,
                },
            },
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [
                {
                    "subject_code": "kpss_turkce",
                    "skill_type": "paragraph_inference",
                    "paragraph_length_avg": 180,
                    "sentence_count_avg": 8,
                    "distractor_pattern": "meaning_shift",
                    "reasoning_type": "inference",
                    "vocabulary_level": "formal",
                    "reading_time_sec_avg": 90,
                    "difficulty_band": "high",
                    "sample_size": 40,
                    "metadata": {
                        "option_similarity": 0.55,
                        "abstraction_level": "moderate_high",
                    },
                },
                {
                    "subject_code": "kpss_matematik",
                    "skill_type": "problem_solving",
                    "paragraph_length_avg": 55,
                    "sentence_count_avg": 4,
                    "distractor_pattern": "half_correct",
                    "reasoning_type": "apply",
                    "vocabulary_level": "formal",
                    "reading_time_sec_avg": 70,
                    "difficulty_band": "high",
                    "sample_size": 40,
                },
            ],
        },
        {
            "exam_code": "tyt",
            "name": "TYT",
            "question_format": "mixed",
            "paragraph_words_min": 90,
            "paragraph_words_max": 260,
            "stem_words_min": 15,
            "stem_words_max": 100,
            "option_words_min": 2,
            "option_words_max": 30,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "analyze",
            "language_level": "formal_tr_yks",
            "reading_time_sec_avg": 80,
            "difficulty_band_default": "high",
            "distractor_types": [
                "close_meaning",
                "detail_trap",
                "overgeneralization",
                "opposite_claim",
            ],
            "style_rules": {
                "tone": "YKS TYT resmi",
                "paragraph_heavy_for_turkce": True,
                "self_contained_stem": True,
                "option_similarity": "medium",
                "option_style": "parallel_length",
                "wording_style": "formal_yks",
                "abstraction_level": "moderate",
                "inference_ratio": 0.62,
                "elimination_ratio": 0.38,
                "bloom_distribution": {
                    "analyze": 0.4,
                    "apply": 0.3,
                    "understand": 0.2,
                    "evaluate": 0.1,
                },
                "reasoning_distribution": {
                    "inference": 0.5,
                    "elimination": 0.3,
                    "comparison": 0.2,
                },
                "skill_distribution": {
                    "main_idea": 0.15,
                    "supporting_idea": 0.15,
                    "vocabulary": 0.12,
                    "paragraph_completion": 0.12,
                    "sentence_ordering": 0.1,
                    "grammar": 0.12,
                    "logic": 0.12,
                    "mixed_reasoning": 0.12,
                },
                "difficulty_distribution": {"easy": 0.2, "medium": 0.45, "hard": 0.35},
                "stem_type_distribution": {
                    "inference": 0.3,
                    "main_idea": 0.2,
                    "paragraph_completion": 0.15,
                    "vocabulary": 0.15,
                    "grammar": 0.2,
                },
            },
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [
                {
                    "subject_code": "tyt_turkce",
                    "skill_type": "paragraph",
                    "paragraph_length_avg": 220,
                    "sentence_count_avg": 10,
                    "distractor_pattern": "close_meaning",
                    "reasoning_type": "inference",
                    "vocabulary_level": "academic_tr",
                    "reading_time_sec_avg": 95,
                    "difficulty_band": "high",
                    "sample_size": 50,
                },
            ],
        },
        {
            "exam_code": "ayt",
            "name": "AYT",
            "question_format": "mixed",
            "paragraph_words_min": 40,
            "paragraph_words_max": 180,
            "stem_words_min": 12,
            "stem_words_max": 100,
            "option_words_min": 2,
            "option_words_max": 35,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "apply",
            "language_level": "formal_tr_yks",
            "reading_time_sec_avg": 85,
            "difficulty_band_default": "high",
            "distractor_types": ["concept_confusion", "formula_misuse", "edge_case"],
            "style_rules": {"tone": "YKS AYT resmi", "self_contained_stem": True},
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [],
        },
        {
            "exam_code": "yks",
            "name": "YKS",
            "question_format": "mixed",
            "paragraph_words_min": 90,
            "paragraph_words_max": 260,
            "stem_words_min": 15,
            "stem_words_max": 100,
            "option_words_min": 2,
            "option_words_max": 30,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "analyze",
            "language_level": "formal_tr_yks",
            "reading_time_sec_avg": 80,
            "difficulty_band_default": "high",
            "distractor_types": ["close_meaning", "detail_trap", "concept_confusion"],
            "style_rules": {"tone": "YKS resmi", "inherits": ["tyt", "ayt"]},
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [],
        },
        {
            "exam_code": "ales",
            "name": "ALES",
            "question_format": "mixed",
            "paragraph_words_min": 50,
            "paragraph_words_max": 160,
            "stem_words_min": 20,
            "stem_words_max": 90,
            "option_words_min": 2,
            "option_words_max": 20,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "analyze",
            "language_level": "formal_tr_academic",
            "reading_time_sec_avg": 70,
            "difficulty_band_default": "high",
            "distractor_types": ["logic_trap", "quantifier_trap", "near_miss"],
            "style_rules": {"tone": "ALES sayısal/sözel resmi", "self_contained_stem": True},
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [],
        },
        {
            "exam_code": "lgs",
            "name": "LGS",
            "question_format": "mixed",
            "paragraph_words_min": 40,
            "paragraph_words_max": 140,
            "stem_words_min": 12,
            "stem_words_max": 70,
            "option_words_min": 2,
            "option_words_max": 22,
            "choice_count": 4,
            "distractor_strength": "balanced",
            "bloom_default": "apply",
            "language_level": "formal_tr_middle",
            "reading_time_sec_avg": 55,
            "difficulty_band_default": "medium",
            "distractor_types": ["calculation_trap", "detail_trap"],
            "style_rules": {"tone": "LGS MEB resmi", "self_contained_stem": True},
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [],
        },
        {
            "exam_code": "dgs",
            "name": "DGS",
            "question_format": "mixed",
            "paragraph_words_min": 40,
            "paragraph_words_max": 140,
            "stem_words_min": 15,
            "stem_words_max": 80,
            "option_words_min": 2,
            "option_words_max": 22,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "apply",
            "language_level": "formal_tr",
            "reading_time_sec_avg": 65,
            "difficulty_band_default": "high",
            "distractor_types": ["calculation_trap", "logic_trap"],
            "style_rules": {"tone": "DGS resmi", "self_contained_stem": True},
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [],
        },
        {
            "exam_code": "yds",
            "name": "YDS",
            "question_format": "mixed",
            "paragraph_words_min": 60,
            "paragraph_words_max": 200,
            "stem_words_min": 10,
            "stem_words_max": 60,
            "option_words_min": 1,
            "option_words_max": 12,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "understand",
            "language_level": "academic_en",
            "reading_time_sec_avg": 70,
            "difficulty_band_default": "high",
            "distractor_types": ["near_synonym", "collocation_trap", "grammar_minimal_pair"],
            "style_rules": {
                "tone": "YDS resmi",
                "language": "en",
                "self_contained_stem": True,
            },
            "avoid_patterns": _avoid_common() + ["Turkish stems for YDS"],
            "source": "estimated",
            "stats": [],
        },
        {
            "exam_code": "yokdil",
            "name": "YÖKDİL",
            "question_format": "mixed",
            "paragraph_words_min": 70,
            "paragraph_words_max": 220,
            "stem_words_min": 10,
            "stem_words_max": 60,
            "option_words_min": 1,
            "option_words_max": 14,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "understand",
            "language_level": "academic_en",
            "reading_time_sec_avg": 75,
            "difficulty_band_default": "high",
            "distractor_types": ["near_synonym", "academic_vocabulary_trap"],
            "style_rules": {"tone": "YÖKDİL resmi", "language": "en"},
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [],
        },
        {
            "exam_code": "ags",
            "name": "AGS",
            "question_format": "mixed",
            "paragraph_words_min": 50,
            "paragraph_words_max": 160,
            "stem_words_min": 15,
            "stem_words_max": 80,
            "option_words_min": 2,
            "option_words_max": 25,
            "choice_count": 5,
            "distractor_strength": "strong",
            "bloom_default": "analyze",
            "language_level": "formal_tr_education",
            "reading_time_sec_avg": 65,
            "difficulty_band_default": "high",
            "distractor_types": ["pedagogy_confusion", "partial_truth"],
            "style_rules": {"tone": "AGS resmi", "self_contained_stem": True},
            "avoid_patterns": _avoid_common(),
            "source": "estimated",
            "stats": [],
        },
    ]
