"""Add eae_interaction to quiz and assessment models

Revision ID: 5217b338bf32
Revises: 624e735a6a58
Create Date: 2026-08-06 12:35:54.157052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "5217b338bf32"
down_revision: Union[str, None] = "624e735a6a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_constraint(op.f("achievements_code_key"), "achievements", type_="unique")
    op.drop_index(op.f("ix_achievements_code"), table_name="achievements")
    op.create_index(op.f("ix_achievements_code"), "achievements", ["code"], unique=True)
    op.drop_index(op.f("ix_activities_user_occurred"), table_name="activities")
    op.create_index(
        op.f("ix_analytics_events_session_id"), "analytics_events", ["session_id"], unique=False
    )
    op.add_column(
        "assessment_questions",
        sa.Column("eae_interaction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        op.f("ix_assessment_sessions_subject_code"),
        "assessment_sessions",
        ["subject_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_sessions_topic_code"),
        "assessment_sessions",
        ["topic_code"],
        unique=False,
    )
    op.alter_column(
        "behavioral_memory",
        "chronotype",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "tempo",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "difficulty_signature",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "acquisition_speed",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "forgetting_curve",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "pomodoro_signature",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "break_signature",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "resource_preference",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "schedule_signature",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "motivation_dips",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "plan_receptivity",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "exam_context",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_index(
        op.f("ix_daily_challenge_scores_day_subject"), table_name="daily_challenge_scores"
    )
    op.drop_index(op.f("ix_daily_challenge_scores_user"), table_name="daily_challenge_scores")
    op.create_index(
        op.f("ix_daily_challenge_scores_challenge_date"),
        "daily_challenge_scores",
        ["challenge_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_challenge_scores_exam_type"),
        "daily_challenge_scores",
        ["exam_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_challenge_scores_subject_code"),
        "daily_challenge_scores",
        ["subject_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_challenge_scores_user_id"),
        "daily_challenge_scores",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_challenges_status"), "daily_challenges", ["status"], unique=False
    )
    op.drop_index(
        op.f("ix_educational_assets_tags_gin"),
        table_name="educational_assets",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_generated_questions_subject_code"),
        "generated_questions",
        ["subject_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_chunks_source_id"), "knowledge_chunks", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_subject_code"), "knowledge_chunks", ["subject_code"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_user_id"), "knowledge_chunks", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_citations_chunk_id"), "knowledge_citations", ["chunk_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_citations_source_id"), "knowledge_citations", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_citations_used_by"), "knowledge_citations", ["used_by"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_citations_user_id"), "knowledge_citations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_notebooks_subject_code"),
        "knowledge_notebooks",
        ["subject_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_sources_study_resource_id"),
        "knowledge_sources",
        ["study_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_sources_subject_code"),
        "knowledge_sources",
        ["subject_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_sources_topic_code"), "knowledge_sources", ["topic_code"], unique=False
    )
    op.drop_index(op.f("ix_qie_human_eval_ref"), table_name="qie_human_evaluations")
    op.drop_index(
        op.f("ix_question_pool_generation_history_exam_subject_topic"),
        table_name="question_pool_generation_history",
    )
    op.create_index(
        op.f("ix_question_pool_generation_history_difficulty_band"),
        "question_pool_generation_history",
        ["difficulty_band"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_pool_generation_history_exam"),
        "question_pool_generation_history",
        ["exam"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_pool_generation_history_subject_code"),
        "question_pool_generation_history",
        ["subject_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_pool_generation_history_topic_code"),
        "question_pool_generation_history",
        ["topic_code"],
        unique=False,
    )
    op.add_column(
        "shared_daily_booklet_questions",
        sa.Column("eae_interaction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        op.f("ix_shared_daily_booklets_status"), "shared_daily_booklets", ["status"], unique=False
    )
    op.alter_column(
        "students",
        "observation_gates",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_constraint(op.f("students_user_id_key"), "students", type_="unique")
    op.drop_index(op.f("ix_students_user_id"), table_name="students")
    op.create_index(op.f("ix_students_user_id"), "students", ["user_id"], unique=True)
    op.drop_index(op.f("ix_study_sessions_topic_code"), table_name="study_sessions")
    op.create_index(
        op.f("ix_study_sessions_subject_code"), "study_sessions", ["subject_code"], unique=False
    )
    op.drop_constraint(op.f("subject_catalog_code_key"), "subject_catalog", type_="unique")
    op.drop_index(op.f("ix_subject_catalog_code"), table_name="subject_catalog")
    op.create_index(op.f("ix_subject_catalog_code"), "subject_catalog", ["code"], unique=True)
    op.alter_column(
        "topic_confidence",
        "history_snapshot",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_index(op.f("ix_topic_confidence_subject"), table_name="topic_confidence")
    op.create_index(
        op.f("ix_topic_confidence_confidence_level"),
        "topic_confidence",
        ["confidence_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_confidence_subject_code"), "topic_confidence", ["subject_code"], unique=False
    )
    op.create_index(
        op.f("ix_topic_confidence_topic_code"), "topic_confidence", ["topic_code"], unique=False
    )
    op.create_index(
        op.f("ix_topic_confidence_user_id"), "topic_confidence", ["user_id"], unique=False
    )
    op.alter_column(
        "topic_evidence",
        "metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_index(op.f("ix_topic_evidence_source"), table_name="topic_evidence")
    op.drop_index(op.f("ix_topic_evidence_user_id"), table_name="topic_evidence")
    op.drop_index(op.f("ix_topic_evidence_category"), table_name="topic_evidence")
    op.create_index(
        op.f("ix_topic_evidence_category"), "topic_evidence", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_topic_evidence_occurred_at"), "topic_evidence", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_topic_evidence_source_id"), "topic_evidence", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_evidence_source_type"), "topic_evidence", ["source_type"], unique=False
    )
    op.add_column(
        "topic_quiz_items",
        sa.Column("eae_interaction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic_quiz_items", "eae_interaction")
    op.drop_index(op.f("ix_topic_evidence_source_type"), table_name="topic_evidence")
    op.drop_index(op.f("ix_topic_evidence_source_id"), table_name="topic_evidence")
    op.drop_index(op.f("ix_topic_evidence_occurred_at"), table_name="topic_evidence")
    op.drop_index(op.f("ix_topic_evidence_category"), table_name="topic_evidence")
    op.create_index(
        op.f("ix_topic_evidence_category"), "topic_evidence", ["user_id", "category"], unique=False
    )
    op.create_index(op.f("ix_topic_evidence_user_id"), "topic_evidence", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_topic_evidence_source"),
        "topic_evidence",
        ["source_type", "source_id"],
        unique=False,
    )
    op.alter_column(
        "topic_evidence",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_index(op.f("ix_topic_confidence_user_id"), table_name="topic_confidence")
    op.drop_index(op.f("ix_topic_confidence_topic_code"), table_name="topic_confidence")
    op.drop_index(op.f("ix_topic_confidence_subject_code"), table_name="topic_confidence")
    op.drop_index(op.f("ix_topic_confidence_confidence_level"), table_name="topic_confidence")
    op.create_index(
        op.f("ix_topic_confidence_subject"), "topic_confidence", ["subject_code"], unique=False
    )
    op.alter_column(
        "topic_confidence",
        "history_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_index(op.f("ix_subject_catalog_code"), table_name="subject_catalog")
    op.create_index(op.f("ix_subject_catalog_code"), "subject_catalog", ["code"], unique=False)
    op.create_unique_constraint(
        op.f("subject_catalog_code_key"),
        "subject_catalog",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_study_sessions_subject_code"), table_name="study_sessions")
    op.create_index(
        op.f("ix_study_sessions_topic_code"), "study_sessions", ["topic_code"], unique=False
    )
    op.drop_index(op.f("ix_students_user_id"), table_name="students")
    op.create_index(op.f("ix_students_user_id"), "students", ["user_id"], unique=False)
    op.create_unique_constraint(
        op.f("students_user_id_key"), "students", ["user_id"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "students",
        "observation_gates",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_index(op.f("ix_shared_daily_booklets_status"), table_name="shared_daily_booklets")
    op.drop_column("shared_daily_booklet_questions", "eae_interaction")
    op.drop_index(
        op.f("ix_question_pool_generation_history_topic_code"),
        table_name="question_pool_generation_history",
    )
    op.drop_index(
        op.f("ix_question_pool_generation_history_subject_code"),
        table_name="question_pool_generation_history",
    )
    op.drop_index(
        op.f("ix_question_pool_generation_history_exam"),
        table_name="question_pool_generation_history",
    )
    op.drop_index(
        op.f("ix_question_pool_generation_history_difficulty_band"),
        table_name="question_pool_generation_history",
    )
    op.create_index(
        op.f("ix_question_pool_generation_history_exam_subject_topic"),
        "question_pool_generation_history",
        ["exam", "subject_code", "topic_code", "difficulty_band"],
        unique=False,
    )
    op.create_index(
        op.f("ix_qie_human_eval_ref"),
        "qie_human_evaluations",
        ["question_ref_type", "question_ref_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_knowledge_sources_topic_code"), table_name="knowledge_sources")
    op.drop_index(op.f("ix_knowledge_sources_subject_code"), table_name="knowledge_sources")
    op.drop_index(op.f("ix_knowledge_sources_study_resource_id"), table_name="knowledge_sources")
    op.drop_index(op.f("ix_knowledge_notebooks_subject_code"), table_name="knowledge_notebooks")
    op.drop_index(op.f("ix_knowledge_citations_user_id"), table_name="knowledge_citations")
    op.drop_index(op.f("ix_knowledge_citations_used_by"), table_name="knowledge_citations")
    op.drop_index(op.f("ix_knowledge_citations_source_id"), table_name="knowledge_citations")
    op.drop_index(op.f("ix_knowledge_citations_chunk_id"), table_name="knowledge_citations")
    op.drop_index(op.f("ix_knowledge_chunks_user_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_subject_code"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_source_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_generated_questions_subject_code"), table_name="generated_questions")
    op.create_index(
        op.f("ix_educational_assets_tags_gin"),
        "educational_assets",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_daily_challenges_status"), table_name="daily_challenges")
    op.drop_index(op.f("ix_daily_challenge_scores_user_id"), table_name="daily_challenge_scores")
    op.drop_index(
        op.f("ix_daily_challenge_scores_subject_code"), table_name="daily_challenge_scores"
    )
    op.drop_index(op.f("ix_daily_challenge_scores_exam_type"), table_name="daily_challenge_scores")
    op.drop_index(
        op.f("ix_daily_challenge_scores_challenge_date"), table_name="daily_challenge_scores"
    )
    op.create_index(
        op.f("ix_daily_challenge_scores_user"), "daily_challenge_scores", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_challenge_scores_day_subject"),
        "daily_challenge_scores",
        ["challenge_date", "subject_code", "exam_type"],
        unique=False,
    )
    op.alter_column(
        "behavioral_memory",
        "exam_context",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "plan_receptivity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "motivation_dips",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "schedule_signature",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "resource_preference",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "break_signature",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "pomodoro_signature",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "forgetting_curve",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "acquisition_speed",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "difficulty_signature",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "tempo",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "behavioral_memory",
        "chronotype",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_index(op.f("ix_assessment_sessions_topic_code"), table_name="assessment_sessions")
    op.drop_index(op.f("ix_assessment_sessions_subject_code"), table_name="assessment_sessions")
    op.drop_column("assessment_questions", "eae_interaction")
    op.drop_index(op.f("ix_analytics_events_session_id"), table_name="analytics_events")
    op.create_index(
        op.f("ix_activities_user_occurred"), "activities", ["user_id", "occurred_at"], unique=False
    )
    op.drop_index(op.f("ix_achievements_code"), table_name="achievements")
    op.create_index(op.f("ix_achievements_code"), "achievements", ["code"], unique=False)
    op.create_unique_constraint(
        op.f("achievements_code_key"), "achievements", ["code"], postgresql_nulls_not_distinct=False
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("token_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "used_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("password_reset_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("password_reset_tokens_pkey")),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###
