"""add study_plans table

Revision ID: c68d9085b762
Revises: e031a8862d10
Create Date: 2026-07-15 19:51:44.401389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c68d9085b762"
down_revision: str | None = "e031a8862d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=True),
        sa.Column("target_question_count", sa.Integer(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("planned_start_time", sa.Time(), nullable=True),
        sa.Column("planned_end_time", sa.Time(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("completed_question_count", sa.Integer(), nullable=False),
        sa.Column("completed_minutes", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("study_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_study_plans_study_date"), "study_plans", ["study_date"], unique=False)
    op.create_index(op.f("ix_study_plans_user_id"), "study_plans", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_study_plans_user_id"), table_name="study_plans")
    op.drop_index(op.f("ix_study_plans_study_date"), table_name="study_plans")
    op.drop_table("study_plans")
    # ### end Alembic commands ###
