"""
StudyOS — Achievement seed katalog (data-driven criteria)
Sprint-2.9 — U1: yeni rozet için servis if/else gerekmez.
"""

from __future__ import annotations

from typing import Any

# criteria: metric + op + value; events opsiyonel filtre
# op: gte | eq | lte | contains (string set in metrics as "__set__:{name}")


def _c(metric: str, value: float | str, *, op: str = "gte", events: list[str] | None = None) -> dict[str, Any]:
    c: dict[str, Any] = {"metric": metric, "op": op, "value": value}
    if events:
        c["events"] = events
    return c


ACHIEVEMENT_SEED: list[dict[str, Any]] = [
    # Pomodoro
    {
        "code": "pomodoro_first",
        "title": "İlk Pomodoro",
        "description": "İlk odak oturumunu tamamla",
        "category": "pomodoro",
        "tier": "easy",
        "points": 10,
        "icon_key": "timer",
        "sort_order": 10,
        "criteria": _c("total_pomodoros", 1, events=["session_completed"]),
    },
    {
        "code": "pomodoro_10",
        "title": "10 Pomodoro",
        "description": "10 Pomodoro tamamla",
        "category": "pomodoro",
        "tier": "easy",
        "points": 20,
        "icon_key": "timer",
        "sort_order": 11,
        "criteria": _c("total_pomodoros", 10, events=["session_completed"]),
    },
    {
        "code": "pomodoro_50",
        "title": "50 Pomodoro",
        "description": "50 Pomodoro tamamla",
        "category": "pomodoro",
        "tier": "medium",
        "points": 40,
        "icon_key": "timer",
        "sort_order": 12,
        "criteria": _c("total_pomodoros", 50, events=["session_completed"]),
    },
    {
        "code": "pomodoro_100",
        "title": "100 Pomodoro",
        "description": "100 Pomodoro tamamla",
        "category": "pomodoro",
        "tier": "hard",
        "points": 80,
        "icon_key": "timer",
        "sort_order": 13,
        "criteria": _c("total_pomodoros", 100, events=["session_completed"]),
    },
    # Study time (minutes)
    {
        "code": "study_30m",
        "title": "İlk Yarım Saat",
        "description": "Toplam 30 dakika çalış",
        "category": "study_time",
        "tier": "easy",
        "points": 10,
        "icon_key": "schedule",
        "sort_order": 20,
        "criteria": _c("total_study_minutes", 30, events=["session_completed"]),
    },
    {
        "code": "study_10h",
        "title": "10 Saat",
        "description": "Toplam 10 saat çalış",
        "category": "study_time",
        "tier": "medium",
        "points": 40,
        "icon_key": "schedule",
        "sort_order": 21,
        "criteria": _c("total_study_minutes", 600, events=["session_completed"]),
    },
    {
        "code": "study_50h",
        "title": "50 Saat",
        "description": "Toplam 50 saat çalış",
        "category": "study_time",
        "tier": "hard",
        "points": 80,
        "icon_key": "schedule",
        "sort_order": 22,
        "criteria": _c("total_study_minutes", 3000, events=["session_completed"]),
    },
    {
        "code": "study_100h",
        "title": "100 Saat",
        "description": "Toplam 100 saat çalış",
        "category": "study_time",
        "tier": "legendary",
        "points": 150,
        "icon_key": "schedule",
        "sort_order": 23,
        "criteria": _c("total_study_minutes", 6000, events=["session_completed"]),
    },
    # Questions
    {
        "code": "questions_10",
        "title": "İlk 10 Soru",
        "description": "10 soru çöz",
        "category": "questions",
        "tier": "easy",
        "points": 10,
        "icon_key": "quiz",
        "sort_order": 30,
        "criteria": _c("total_questions", 10),
    },
    {
        "code": "questions_100",
        "title": "100 Soru",
        "description": "100 soru çöz",
        "category": "questions",
        "tier": "easy",
        "points": 25,
        "icon_key": "quiz",
        "sort_order": 31,
        "criteria": _c("total_questions", 100),
    },
    {
        "code": "questions_500",
        "title": "500 Soru",
        "description": "500 soru çöz",
        "category": "questions",
        "tier": "medium",
        "points": 50,
        "icon_key": "quiz",
        "sort_order": 32,
        "criteria": _c("total_questions", 500),
    },
    {
        "code": "questions_1000",
        "title": "1000 Soru",
        "description": "1000 soru çöz",
        "category": "questions",
        "tier": "hard",
        "points": 100,
        "icon_key": "quiz",
        "sort_order": 33,
        "criteria": _c("total_questions", 1000),
    },
    # Exam
    {
        "code": "exam_first",
        "title": "İlk Deneme",
        "description": "İlk deneme sınavını kaydet",
        "category": "exam",
        "tier": "easy",
        "points": 15,
        "icon_key": "assignment",
        "sort_order": 40,
        "criteria": _c("exam_count", 1, events=["exam_completed"]),
    },
    {
        "code": "exam_tenth",
        "title": "10. Deneme",
        "description": "10 deneme kaydet",
        "category": "exam",
        "tier": "medium",
        "points": 40,
        "icon_key": "assignment",
        "sort_order": 41,
        "criteria": _c("exam_count", 10, events=["exam_completed"]),
    },
    {
        "code": "exam_record_net",
        "title": "Net Rekoru",
        "description": "Kişisel net rekorunu kır",
        "category": "exam",
        "tier": "hard",
        "points": 60,
        "icon_key": "assignment",
        "sort_order": 42,
        "criteria": _c("exam_milestone_new_record_net", 1, op="eq", events=["exam_completed"]),
    },
    # Revision
    {
        "code": "revision_first",
        "title": "İlk Tekrar",
        "description": "İlk spaced-repetition review",
        "category": "revision",
        "tier": "easy",
        "points": 10,
        "icon_key": "replay",
        "sort_order": 50,
        "criteria": _c("revision_reviews", 1, events=["revision_reviewed"]),
    },
    {
        "code": "revision_25",
        "title": "25 Tekrar",
        "description": "25 review tamamla",
        "category": "revision",
        "tier": "medium",
        "points": 40,
        "icon_key": "replay",
        "sort_order": 51,
        "criteria": _c("revision_reviews", 25, events=["revision_reviewed"]),
    },
    {
        "code": "revision_mastered_10",
        "title": "10 Mastered",
        "description": "10 kartı mastered yap",
        "category": "revision",
        "tier": "hard",
        "points": 70,
        "icon_key": "replay",
        "sort_order": 52,
        "criteria": _c("revision_mastered", 10, events=["revision_reviewed", "revision_completed"]),
    },
    # Goals
    {
        "code": "goal_milestone_25",
        "title": "Hedefte %25",
        "description": "Bir hedefte %25 milestone",
        "category": "goal",
        "tier": "easy",
        "points": 15,
        "icon_key": "flag",
        "sort_order": 60,
        "criteria": _c("goal_milestone_25_hits", 1, events=["goal_progress"]),
    },
    {
        "code": "goal_completed_first",
        "title": "İlk Hedef",
        "description": "Bir hedefi %100 tamamla",
        "category": "goal",
        "tier": "medium",
        "points": 40,
        "icon_key": "flag",
        "sort_order": 61,
        "criteria": _c("goals_completed", 1, events=["goal_progress"]),
    },
    {
        "code": "goal_completed_5",
        "title": "5 Hedef",
        "description": "5 hedef tamamla",
        "category": "goal",
        "tier": "hard",
        "points": 80,
        "icon_key": "flag",
        "sort_order": 62,
        "criteria": _c("goals_completed", 5, events=["goal_progress"]),
    },
    # Planner
    {
        "code": "planner_first_generate",
        "title": "İlk AI Plan",
        "description": "İlk adaptive plan taslağını oluştur",
        "category": "planner",
        "tier": "easy",
        "points": 15,
        "icon_key": "auto_awesome",
        "sort_order": 70,
        "criteria": _c("planner_generated_count", 1, events=["planner_generated"]),
    },
    {
        "code": "planner_first_accept",
        "title": "Plan Kabul",
        "description": "İlk planı kabul et",
        "category": "planner",
        "tier": "easy",
        "points": 20,
        "icon_key": "auto_awesome",
        "sort_order": 71,
        "criteria": _c("planner_accepted_count", 1, events=["planner_accepted"]),
    },
    {
        "code": "planner_accept_5",
        "title": "5 Plan Kabul",
        "description": "5 adaptive plan kabul et",
        "category": "planner",
        "tier": "medium",
        "points": 50,
        "icon_key": "auto_awesome",
        "sort_order": 72,
        "criteria": _c("planner_accepted_count", 5, events=["planner_accepted"]),
    },
    # Streak
    {
        "code": "streak_3",
        "title": "3 Gün Seri",
        "description": "3 gün üst üste çalış",
        "category": "streak",
        "tier": "easy",
        "points": 20,
        "icon_key": "local_fire_department",
        "sort_order": 80,
        "criteria": _c("streak_days", 3, events=["session_completed"]),
    },
    {
        "code": "streak_7",
        "title": "7 Gün Seri",
        "description": "7 gün üst üste çalış",
        "category": "streak",
        "tier": "medium",
        "points": 50,
        "icon_key": "local_fire_department",
        "sort_order": 81,
        "criteria": _c("streak_days", 7, events=["session_completed"]),
    },
    {
        "code": "streak_30",
        "title": "30 Gün Seri",
        "description": "30 gün üst üste çalış",
        "category": "streak",
        "tier": "legendary",
        "points": 150,
        "icon_key": "local_fire_department",
        "sort_order": 82,
        "criteria": _c("streak_days", 30, events=["session_completed"]),
    },
]
