"""Aggregate Style DNA profile for an exam code."""

from __future__ import annotations

from typing import Any

from app.services.exam_intelligence.parser.types import ParseResult


def build_style_dna(results: list[ParseResult], exam_code: str) -> dict[str, Any]:
    rs = [r for r in results if r.exam_code == exam_code]
    if not rs:
        return {
            "exam_code": exam_code,
            "style_version": "m27_v1",
            "source": "m27_parser_empty",
        }

    all_q = [q for r in rs for q in r.questions]
    n = max(len(all_q), 1)
    long_para = sum(1 for q in all_q if q.estimated_reading_length_words >= 80)
    inference = sum(1 for q in all_q if q.skill_type == "inference")
    avg_words = sum(q.estimated_reading_length_words for q in all_q) / n
    avg_diff = sum(q.estimated_difficulty for q in all_q) / n
    avg_read = sum(q.estimated_reading_time_sec for q in all_q) / n
    avg_opt = sum(q.option_length_avg for q in all_q) / n
    multi = sum(1 for q in all_q if q.multi_step) / n

    easy = sum(1 for q in all_q if q.estimated_difficulty < 45) / n
    med = sum(1 for q in all_q if 45 <= q.estimated_difficulty < 70) / n
    hard = sum(1 for q in all_q if q.estimated_difficulty >= 70) / n

    reading_load = (
        "very_high" if avg_words >= 140 else ("high" if avg_words >= 90 else "medium")
    )
    time_pressure = "high" if avg_read >= 40 else ("moderate_high" if avg_read >= 25 else "moderate")

    return {
        "exam_code": exam_code,
        "name": exam_code.upper(),
        "style_version": "m27_v1",
        "source": "m27_parser",
        "sessions_parsed": len(rs),
        "question_sample_size": len(all_q),
        "choice_count": 5 if exam_code != "lgs" else 4,
        "paragraph_ratio": round(long_para / n, 3),
        "paragraph_length_avg": round(avg_words, 1),
        "reasoning_ratio": round(inference / n, 3),
        "reasoning_style": "inference_heavy" if inference / n >= 0.3 else "mixed",
        "reading_load": reading_load,
        "language_level": "formal_tr" if rs[0].language == "tr" else "academic_en",
        "bloom_distribution": {
            "understand": round(easy * 0.6, 3),
            "apply": round(med * 0.7, 3),
            "analyze": round(hard * 0.75 + med * 0.3, 3),
            "evaluate": round(hard * 0.25, 3),
        },
        "difficulty_curve": {
            "easy": round(easy, 3),
            "medium": round(med, 3),
            "hard": round(hard, 3),
        },
        "difficulty_band": "high" if avg_diff >= 65 else ("medium_high" if avg_diff >= 55 else "medium"),
        "option_balance": "tight" if avg_opt >= 5 else "short",
        "option_length_avg": round(avg_opt, 2),
        "distractor_style": "plausible_heuristic",
        "time_pressure": time_pressure,
        "reading_time_sec_avg": round(avg_read, 1),
        "question_ordering": rs[0].subject_order or [],
        "multi_step_ratio": round(multi, 3),
        "notes": "Generated by M27 Official Exam Parser. No question text stored.",
    }
